# Generated by Django 2.0 on 2019-04-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myweek',
            old_name='date',
            new_name='week_date',
        ),
    ]
